"$schema" = 'https://starship.rs/config-schema.json'

palette = 'theme'
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character"""

right_format = """
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$conda\
$time"""

[directory]
style = "peach"
format = "[$path ]($style)"
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "yellow"
format = '[$symbol $branch ]($style)'

[git_status]
style = "yellow"
format = '([$all_status$ahead_behind ]($style))'

[nodejs]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[bun]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[c]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[rust]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[golang]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[php]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[java]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[python]
symbol = ""
style = "green"
format = '[$symbol( $version)(\(#$virtualenv\)) ]($style)'

[docker_context]
symbol = ""
style = "sapphire"
format = '[$symbol( $context) ]($style)'

[conda]
symbol = ""
style = "sapphire"
format = '[ $symbol $environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "lavender"
format = '[ $time ]($style)'

[character]
disabled = false
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[⬅](bold green)'
vimcmd_replace_one_symbol = '[⬅](bold lavender)'
vimcmd_replace_symbol = '[⬅](bold lavender)'
vimcmd_visual_symbol = '[⬅](bold yellow)'

[palettes.theme]
bg = "#1f1f1f"
fg = "#cccccc"
black = "#3c3c3c"
red = "#f44747"
green = "#6a9955"
yellow = "#dcdcaa"
blue = "#4fc1ff"
magenta = "#c586c0"
cyan = "#9cdcfe"
white = "#d4d4d4"
peach = "#dcdcaa"
sapphire = "#4fc1ff"
lavender = "#c586c0"
text = "#cccccc"
base = "#1f1f1f"
mantle = "#1f1f1f"
crust = "#1f1f1f"
surface0 = "#3c3c3c"
overlay0 = "#d4d4d4"
