use anyhow::{Context, Result};
use owo_colors::OwoColorize;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ThemeData {
    #[serde(default = "default_theme_name")]
    pub name: String,
    pub bg: String,
    pub fg: String,
    pub black: String,
    pub red: String,
    pub green: String,
    pub yellow: String,
    pub blue: String,
    pub magenta: String,
    pub cyan: String,
    pub white: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

fn default_theme_name() -> String {
    "Custom".to_string()
}

impl ThemeData {
    /// Return the list of color key-value pairs in standard order.
    pub fn colors(&self) -> Vec<(&str, &str)> {
        let mut list = vec![
            ("bg", self.bg.as_str()),
            ("fg", self.fg.as_str()),
            ("black", self.black.as_str()),
            ("red", self.red.as_str()),
            ("green", self.green.as_str()),
            ("yellow", self.yellow.as_str()),
            ("blue", self.blue.as_str()),
            ("magenta", self.magenta.as_str()),
            ("cyan", self.cyan.as_str()),
            ("white", self.white.as_str()),
        ];
        for (k, v) in &self.extra {
            if let Some(s) = v.as_str() {
                list.push((k.as_str(), s));
            }
        }
        list
    }
}

pub fn generate_lua(theme: &ThemeData) -> String {
    let mut out = String::from("-- Auto-generated by Theme Engine\nreturn {\n");
    for (key, value) in theme.colors() {
        out.push_str(&format!("  {} = \"{}\",\n", key, value));
    }
    out.push_str("}\n");
    out
}

pub fn generate_sh(theme: &ThemeData) -> String {
    let mut out = String::from("# Auto-generated by Theme Engine\n");
    out.push_str(&format!("export THEME_NAME=\"{}\"\n", theme.name));
    out.push_str(&format!("export BAT_THEME=\"{}\"\n", theme.name));
    for (key, value) in theme.colors() {
        out.push_str(&format!(
            "export THEME_{}=\"{}\"\n",
            key.to_uppercase(),
            value
        ));
    }
    out
}

pub fn generate_ps1(theme: &ThemeData) -> String {
    let mut out = String::from("# Auto-generated by Theme Engine\n");
    out.push_str(&format!("$env:THEME_NAME=\"{}\"\n", theme.name));
    out.push_str(&format!("$env:BAT_THEME=\"{}\"\n", theme.name));
    for (key, value) in theme.colors() {
        out.push_str(&format!(
            "$env:THEME_{}=\"{}\"\n",
            key.to_uppercase(),
            value
        ));
    }
    out
}

pub fn update_bat_config(dotfiles_dir: &Path, theme: &ThemeData) -> Result<()> {
    let bat_config_path = dotfiles_dir.join("apps").join("bat").join("config");
    if !bat_config_path.exists()
        && let Some(parent) = bat_config_path.parent()
    {
        let _ = fs::create_dir_all(parent);
    }

    let content = if bat_config_path.exists() {
        fs::read_to_string(&bat_config_path).unwrap_or_default()
    } else {
        String::new()
    };

    let theme_line = format!("--theme=\"{}\"", theme.name);

    let new_content = if content.contains("--theme=") {
        content
            .lines()
            .map(|line| {
                if line.trim().starts_with("--theme=") {
                    theme_line.clone()
                } else {
                    line.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        format!("{}\n\n{}", theme_line, content)
    };

    fs::write(&bat_config_path, format!("{}\n", new_content.trim()))
        .with_context(|| format!("Không thể ghi tệp: {}", bat_config_path.display()))?;

    Ok(())
}

pub fn generate_atuin_theme(theme: &ThemeData) -> String {
    format!(
        r#"# Auto-generated by Theme Engine for Atuin
[theme]
name = "theme"
parent = "default"

[colors]
AlertInfo = "{blue}"
AlertWarn = "{yellow}"
AlertError = "{red}"
Annotation = "{cyan}"
Base = "{fg}"
Guidance = "{green}"
Important = "{magenta}"
Title = "{blue}"
Muted = "{black}"
SyntaxCommand = "{blue}"
SyntaxFlag = "{cyan}"
SyntaxString = "{green}"
SyntaxVariable = "{magenta}"
SyntaxOperator = "{cyan}"
SyntaxComment = "{black}"
"#,
        blue = theme.blue,
        yellow = theme.yellow,
        red = theme.red,
        cyan = theme.cyan,
        fg = theme.fg,
        green = theme.green,
        magenta = theme.magenta,
        black = theme.black
    )
}

pub fn generate_starship_palette(theme: &ThemeData) -> String {
    format!(
        r#"[palettes.theme]
bg = "{bg}"
fg = "{fg}"
black = "{black}"
red = "{red}"
green = "{green}"
yellow = "{yellow}"
blue = "{blue}"
magenta = "{magenta}"
cyan = "{cyan}"
white = "{white}"
peach = "{yellow}"
sapphire = "{blue}"
lavender = "{magenta}"
text = "{fg}"
base = "{bg}"
mantle = "{bg}"
crust = "{bg}"
surface0 = "{black}"
overlay0 = "{white}"
"#,
        bg = theme.bg,
        fg = theme.fg,
        black = theme.black,
        red = theme.red,
        green = theme.green,
        yellow = theme.yellow,
        blue = theme.blue,
        magenta = theme.magenta,
        cyan = theme.cyan,
        white = theme.white,
    )
}

pub fn update_starship_config(dotfiles_dir: &Path, theme: &ThemeData) -> Result<()> {
    let starship_path = dotfiles_dir
        .join("apps")
        .join("starship")
        .join("starship.toml");
    if !starship_path.exists() {
        return Ok(());
    }

    let content = fs::read_to_string(&starship_path)
        .with_context(|| format!("Không thể đọc tệp: {}", starship_path.display()))?;

    // Find where [palettes begins or keep config before [palettes
    let base_content = if let Some(idx) = content.find("[palettes") {
        content[..idx].trim_end().to_string()
    } else {
        content.trim_end().to_string()
    };

    // Ensure palette = 'theme' is set
    let updated_base = if let Some(pos) = base_content.find("palette =") {
        let line_end = base_content[pos..]
            .find('\n')
            .map(|p| pos + p)
            .unwrap_or(base_content.len());
        format!(
            "{}palette = 'theme'{}",
            &base_content[..pos],
            &base_content[line_end..]
        )
    } else {
        base_content
    };

    let palette_section = generate_starship_palette(theme);
    let new_content = format!("{}\n\n{}\n", updated_base.trim(), palette_section.trim());

    fs::write(&starship_path, new_content)
        .with_context(|| format!("Không thể ghi tệp: {}", starship_path.display()))?;

    Ok(())
}

/// Parses theme.json and directly generates destination config files:
/// - themes/generated/theme.lua (Neovim, WezTerm)
/// - themes/generated/theme.sh (Bash, Zsh)
/// - themes/generated/theme.ps1 (PowerShell)
/// - apps/atuin/themes/theme.toml (Atuin)
/// - apps/starship/starship.toml (Starship Prompt palette)
pub fn generate_themes(dotfiles_dir: &Path) -> Result<ThemeData> {
    let theme_json_path = dotfiles_dir.join("themes").join("theme.json");
    let content = fs::read_to_string(&theme_json_path)
        .with_context(|| format!("Không thể đọc tệp theme: {}", theme_json_path.display()))?;

    let theme_data: ThemeData = serde_json::from_str(&content)
        .with_context(|| format!("Lỗi phân tích JSON từ: {}", theme_json_path.display()))?;

    let out_dir = dotfiles_dir.join("themes").join("generated");
    let atuin_themes_dir = dotfiles_dir.join("apps").join("atuin").join("themes");

    fs::create_dir_all(&out_dir)
        .with_context(|| format!("Không thể tạo thư mục: {}", out_dir.display()))?;
    fs::create_dir_all(&atuin_themes_dir)
        .with_context(|| format!("Không thể tạo thư mục: {}", atuin_themes_dir.display()))?;

    fs::write(out_dir.join("theme.lua"), generate_lua(&theme_data))
        .with_context(|| "Không thể ghi tệp theme.lua")?;
    fs::write(out_dir.join("theme.sh"), generate_sh(&theme_data))
        .with_context(|| "Không thể ghi tệp theme.sh")?;
    fs::write(out_dir.join("theme.ps1"), generate_ps1(&theme_data))
        .with_context(|| "Không thể ghi tệp theme.ps1")?;

    fs::write(
        atuin_themes_dir.join("theme.toml"),
        generate_atuin_theme(&theme_data),
    )
    .with_context(|| "Không thể ghi tệp atuin theme.toml")?;

    // Synchronize Starship prompt palette
    if let Err(e) = update_starship_config(dotfiles_dir, &theme_data) {
        eprintln!(
            "{}",
            format!("  [!] Không thể cập nhật Starship config: {}", e).yellow()
        );
    }

    // Synchronize Bat theme
    if let Err(e) = update_bat_config(dotfiles_dir, &theme_data) {
        eprintln!(
            "{}",
            format!("  [!] Không thể cập nhật Bat config: {}", e).yellow()
        );
    }

    Ok(theme_data)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_theme() -> ThemeData {
        serde_json::from_str(
            r##"{
            "name": "Catppuccin Mocha",
            "bg": "#1e1e2e",
            "fg": "#cdd6f4",
            "black": "#45475a",
            "red": "#f38ba8",
            "green": "#a6e3a1",
            "yellow": "#f9e2af",
            "blue": "#89b4fa",
            "magenta": "#f5c2e7",
            "cyan": "#94e2d5",
            "white": "#bac2de"
        }"##,
        )
        .unwrap()
    }

    #[test]
    fn test_theme_generation_output() {
        let theme = sample_theme();

        let lua = generate_lua(&theme);
        assert!(lua.contains("bg = \"#1e1e2e\","));
        assert!(lua.contains("fg = \"#cdd6f4\","));

        let sh = generate_sh(&theme);
        assert!(sh.contains("export THEME_BG=\"#1e1e2e\""));

        let ps1 = generate_ps1(&theme);
        assert!(ps1.contains("$env:THEME_BG=\"#1e1e2e\""));

        let atuin = generate_atuin_theme(&theme);
        assert!(atuin.contains("AlertInfo = \"#89b4fa\""));

        let starship = generate_starship_palette(&theme);
        assert!(starship.contains("[palettes.theme]"));
        assert!(starship.contains("bg = \"#1e1e2e\""));
    }
}
